spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # dialect: org.hibernate.dialect.Oracle19cDialect  # uncomment if needed

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR
